//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPoint.DataAccess.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013/_vti_bin/views.asmx")]
        public string BPoint_DataAccess_WebServices_ViewsWebService_Views {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_ViewsWebService_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013/_vti_bin/lists.asmx")]
        public string BPoint_DataAccess_WebServices_ListsWebService_Lists {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_ListsWebService_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013/_vti_bin/webs.asmx")]
        public string BPoint_DataAccess_WebServices_WebsWebService_Webs {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_WebsWebService_Webs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013/_vti_bin/sitedata.asmx")]
        public string BPoint_DataAccess_WebServices_SiteDataWebService_SiteData {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_SiteDataWebService_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013/_vti_bin/taxonomyclientservice.asmx")]
        public string BPoint_DataAccess_WebServices_TaxonomyWebService_Taxonomy_x0020_web_x0020_service {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_TaxonomyWebService_Taxonomy_x0020_web_x0020_service" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sp2013-as1/_vti_bin/usergroup.asmx")]
        public string BPoint_DataAccess_WebServices_UserGroupWebService_UserGroup {
            get {
                return ((string)(this["BPoint_DataAccess_WebServices_UserGroupWebService_UserGroup"]));
            }
        }
    }
}
